on: push
name: Build
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Run test
        uses: cedrickring/golang-action@1.4.1
        with:
          args: make unit-test

      - name: Bulid linux binary
        uses: cedrickring/golang-action@1.4.1
        with:
          args: make build-linux
