# Set encryptor for encryping passwords. Ex: "AES"
encryptorID: "AES"
# Maximum list size for selection drop down.
selectListSize: 5
# Set storage configurations.
storage:
  # File storage configuration.
  file:
    # Enable File storage.
    enable: true
    # Path for the file.
    path: "~/password-manager/passwordDB"
    # File permission for given file in the path.
    permission: 0640
  # Google Drive storage configuration.
  googleDrive:
    # Enable Google Drive storage.
    enable: false
    # Directory where the password Database file resides.
    directory: "password-manager"
    # Password Database file name.
    passwordDBFile: "passwordDB"
    # Path for the Google drive token file.
    tokenFile: "~/password-manager/tokenFile"
